// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/pivot-bounce-explainer/GatesChecklist.tsx": () => import("../components/mockups/pivot-bounce-explainer/GatesChecklist.tsx"),
  "./components/mockups/pivot-bounce-explainer/PivotFormula.tsx": () => import("../components/mockups/pivot-bounce-explainer/PivotFormula.tsx"),
  "./components/mockups/pivot-bounce-explainer/TradeDiagram.tsx": () => import("../components/mockups/pivot-bounce-explainer/TradeDiagram.tsx"),
  "./components/mockups/pivot-bounce-explainer/ZoneDiagram.tsx": () => import("../components/mockups/pivot-bounce-explainer/ZoneDiagram.tsx")
};
