import {
  pgTable,
  serial,
  text,
  doublePrecision,
  boolean,
  bigint,
  timestamp,
} from "drizzle-orm/pg-core";

export const closedTradesTable = pgTable("closed_trades", {
  id: serial("id").primaryKey().notNull(),
  key: text("key").notNull(),
  symbol: text("symbol").notNull(),
  timeframe: text("timeframe").notNull(),
  signal: text("signal").notNull(),
  signalType: text("signal_type").notNull(),
  entryPrice: doublePrecision("entry_price").notNull(),
  stopLoss: doublePrecision("stop_loss").notNull(),
  takeProfit1: doublePrecision("take_profit1").notNull(),
  takeProfit2: doublePrecision("take_profit2").notNull(),
  riskRewardRatio: doublePrecision("risk_reward_ratio").notNull(),
  exitPrice: doublePrecision("exit_price").notNull(),
  outcome: text("outcome").notNull(),
  rMultiple: doublePrecision("r_multiple").notNull(),
  tp1Hit: boolean("tp1_hit").notNull().default(false),
  openedAt: bigint("opened_at", { mode: "number" }),
  closedAt: bigint("closed_at", { mode: "number" }).notNull(),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow(),
});
